#define __VehicleState_h
class VehicleState {
public:
  void init();
  void setVolts(float volts);
  float getVolts();
  int getFuelLevel();
  void setFuelLevel(int fuelLevel);
  float getFuelLeters();
  void setSpeedMPH(float mph);
  float getSpeedMPH();
  float getSpeedKPH();
  void setRPMs(int rpm);
  int getRPMs();
  void setOilPSI(float psi);
  float getOilPSI();
  void setTempF(float deg_f);
  void setTempC(float deg_c);
  float getTempF();
  float getTempC();
  void patsOn();
  void patsOff();
  void setPats(bool status);
  bool getPats();
  void cruiseLampOn();
  void cruiseLampOff();
  void setCruiseLamp(bool status);
  bool getCruiseLamp();
  void shiftLampOn();
  void shiftLampOff();
  void setShiftLamp(bool status);
  bool getShiftLamp();
  void celOn();
  void celOff();
  void setCel(bool status);
  bool getCel();
  void checkGaugesOn();
  void checkGaugesOff();
  void setCheckGauges(bool state);
  bool getCheckGauges();
  void airbagLampOn();
  void airbagLampOff();
  void setAirbagLamp(bool status);
  bool getAirbagLamp();
private:
  float volts;
  float fuelLevel;
  int tankCapacity = 30;
  float kph;
  float mph;
  int rpm;
  float psi;
  float deg_c;
  float deg_f;
  bool pats_illuminated;
  bool cruise_illuminated;
  bool shift_illuminated;
  bool cel_illuminated;
  bool checkGauges_illuminated;
  bool airbag_illuminated;
};